import type { Route } from '@/interfaces';
import { lineString } from '@turf/turf';
import {
  ROUTE_1,
  ROUTE_2,
  ROUTE_3,
  ROUTE_4,
  ROUTE_5,
  ROUTE_6,
  ROUTE_7,
  ROUTE_8,
  ROUTE_9,
  ROUTE_10,
  ROUTE_11,
  ROUTE_12,
  ROUTE_13,
  ACACIA,
  BAGO_APLAYA,
  BANGKAL,
  BARACATAN_TORIL_DARONG,
  BAGUIO,
  BUHANGIN_VIA_DACUDAO,
  BUHANGIN_VIA_JP_LAUREL,
  BUNAWAN_BUHANGIN,
  BUNAWAN_SASA,
  CALINAN,
  CALLAWA,
  CATALUNAN_GRANDE,
  CATITIPAN_DACUDAO,
  CATITIPAN_JP_LAUREL,
  COMMUNAL,
  COUNTRY_HOMES,
  DECA_TACUNAN_AIRCON,
  DONA_PILAR,
  ECOLAND_SM,
  EL_RIO,
  EMILY_HOMES_CABANTIAN,
  INDANGAN,
  JADE_VALLEY_BANGKEROHAN,
  JADE_VALLEY_BUHANGIN,
  JULIVILLE,
  LANDMARK_3,
  LASANG_BUHANGIN,
  LASANG_SASA,
  MAA_AGDAO,
  MAA_BANGKEROHAN,
  MAHAYAG,
  MANDUG,
  MARAHAN,
  MARILOG,
  MATINA,
  MATINA_APLAYA,
  MATINA_CROSSING,
  MATINA_PANGI,
  MINTAL,
  MULIG_TORIL,
  OBRERO,
  PANABO,
  PANABO_BUHANGIN,
  PANACAN_CABAGUIO,
  PANACAN_JP_LAUREL,
  PANACAN_SM,
  PUAN,
  SASA_CABAGUIO,
  SASA_JP_LAUREL,
  SASA_R_CASTILLO,
  SURAYA_HOMES,
  TALOMO,
  TIBUNGCO_BUHANGIN,
  TIBUNGCO_CABAGUIO,
  TIBUNGCO_R_CASTILLO,
  TORIL,
  TUGBOK,
  ULAS,
} from './routes';

export const routeOptions: Route[] = [
  {
    name: 'Route 1 (Inbound)',
    route: lineString(ROUTE_1.INBOUND),
    color: '#FF6B6B',
  },
  {
    name: 'Route 1 (Outbound)',
    route: lineString(ROUTE_1.OUTBOUND),
    color: '#4ECDC4',
  },
  {
    name: 'Route 2 (Inbound)',
    route: lineString(ROUTE_2.INBOUND),
    color: '#45B7D1',
  },
  {
    name: 'Route 2 (Outbound)',
    route: lineString(ROUTE_2.OUTBOUND),
    color: '#96CEB4',
  },
  {
    name: 'Route 3 (Inbound)',
    route: lineString(ROUTE_3.INBOUND),
    color: '#FFEAA7',
  },
  {
    name: 'Route 3 (Outbound)',
    route: lineString(ROUTE_3.OUTBOUND),
    color: '#DDA0DD',
  },
  {
    name: 'Route 4 (Inbound)',
    route: lineString(ROUTE_4.INBOUND),
    color: '#98D8C8',
  },
  {
    name: 'Route 4 (Outbound)',
    route: lineString(ROUTE_4.OUTBOUND),
    color: '#F7DC6F',
  },
  {
    name: 'Route 5 (Inbound)',
    route: lineString(ROUTE_5.INBOUND),
    color: '#BB8FCE',
  },
  {
    name: 'Route 5 (Outbound)',
    route: lineString(ROUTE_5.OUTBOUND),
    color: '#85C1E9',
  },
  {
    name: 'Route 6 (Inbound)',
    route: lineString(ROUTE_6.INBOUND),
    color: '#F8C471',
  },
  {
    name: 'Route 6 (Outbound)',
    route: lineString(ROUTE_6.OUTBOUND),
    color: '#82E0AA',
  },
  {
    name: 'Route 7 (Inbound)',
    route: lineString(ROUTE_7.INBOUND),
    color: '#F1948A',
  },
  {
    name: 'Route 7 (Outbound)',
    route: lineString(ROUTE_7.OUTBOUND),
    color: '#85C1E9',
  },
  {
    name: 'Route 8 (Inbound)',
    route: lineString(ROUTE_8.INBOUND),
    color: '#D7BDE2',
  },
  {
    name: 'Route 8 (Outbound)',
    route: lineString(ROUTE_8.OUTBOUND),
    color: '#F9E79F',
  },
  {
    name: 'Route 9 (Inbound)',
    route: lineString(ROUTE_9.INBOUND),
    color: '#A9CCE3',
  },
  {
    name: 'Route 9 (Outbound)',
    route: lineString(ROUTE_9.OUTBOUND),
    color: '#FAD7A0',
  },
  {
    name: 'Route 10 (Inbound)',
    route: lineString(ROUTE_10.INBOUND),
    color: '#D5A6BD',
  },
  {
    name: 'Route 10 (Outbound)',
    route: lineString(ROUTE_10.OUTBOUND),
    color: '#AED6F1',
  },
  {
    name: 'Route 11 (Inbound)',
    route: lineString(ROUTE_11.INBOUND),
    color: '#F7DC6F',
  },
  {
    name: 'Route 11 (Outbound)',
    route: lineString(ROUTE_11.OUTBOUND),
    color: '#D2B4DE',
  },
  {
    name: 'Route 12 (Inbound)',
    route: lineString(ROUTE_12.INBOUND),
    color: '#A3E4D7',
  },
  {
    name: 'Route 12 (Outbound)',
    route: lineString(ROUTE_12.OUTBOUND),
    color: '#F8C471',
  },
  {
    name: 'Route 13 (Inbound)',
    route: lineString(ROUTE_13.INBOUND),
    color: '#E8DAEF',
  },
  {
    name: 'Route 13 (Outbound)',
    route: lineString(ROUTE_13.OUTBOUND),
    color: '#FADBD8',
  },
  {
    name: 'Acacia (Inbound)',
    route: lineString(ACACIA.INBOUND),
    color: '#D5DBDB',
  },
  {
    name: 'Acacia (Outbound)',
    route: lineString(ACACIA.OUTBOUND),
    color: '#AEB6BF',
  },
  {
    name: 'Bago Aplaya (Inbound)',
    route: lineString(BAGO_APLAYA.INBOUND),
    color: '#85929E',
  },
  {
    name: 'Bago Aplaya (Outbound)',
    route: lineString(BAGO_APLAYA.OUTBOUND),
    color: '#5D6D7E',
  },
  {
    name: 'Bangkal (Inbound)',
    route: lineString(BANGKAL.INBOUND),
    color: '#34495E',
  },
  {
    name: 'Bangkal (Outbound)',
    route: lineString(BANGKAL.OUTBOUND),
    color: '#2E4053',
  },
  {
    name: 'Baracatan/Toril/Darong (Inbound)',
    route: lineString(BARACATAN_TORIL_DARONG.INBOUND),
    color: '#283747',
  },
  {
    name: 'Baracatan/Toril/Darong (Outbound)',
    route: lineString(BARACATAN_TORIL_DARONG.OUTBOUND),
    color: '#212F3C',
  },
  {
    name: 'Baguio District - Roxas (Inbound)',
    route: lineString(BAGUIO.INBOUND),
    color: '#1B2631',
  },
  {
    name: 'Baguio District - Roxas (Outbound)',
    route: lineString(BAGUIO.OUTBOUND),
    color: '#17202A',
  },
  {
    name: 'Buhangin via Dacudao (Inbound)',
    route: lineString(BUHANGIN_VIA_DACUDAO.INBOUND),
    color: '#E74C3C',
  },
  {
    name: 'Buhangin via Dacudao (Outbound)',
    route: lineString(BUHANGIN_VIA_DACUDAO.OUTBOUND),
    color: '#CB4335',
  },
  {
    name: 'Buhangin via JP Laurel (Inbound)',
    route: lineString(BUHANGIN_VIA_JP_LAUREL.INBOUND),
    color: '#A93226',
  },
  {
    name: 'Buhangin via JP Laurel (Outbound)',
    route: lineString(BUHANGIN_VIA_JP_LAUREL.OUTBOUND),
    color: '#922B21',
  },
  {
    name: 'Bunawan via Buhangin (Inbound)',
    route: lineString(BUNAWAN_BUHANGIN.INBOUND),
    color: '#7B241C',
  },
  {
    name: 'Bunawan via Buhangin (Outbound)',
    route: lineString(BUNAWAN_BUHANGIN.OUTBOUND),
    color: '#641E16',
  },
  {
    name: 'Bunawan via Sasa (Inbound)',
    route: lineString(BUNAWAN_SASA.INBOUND),
    color: '#E67E22',
  },
  {
    name: 'Bunawan via Sasa (Outbound)',
    route: lineString(BUNAWAN_SASA.OUTBOUND),
    color: '#D68910',
  },
  {
    name: 'Calinan (Inbound)',
    route: lineString(CALINAN.INBOUND),
    color: '#B7950B',
  },
  {
    name: 'Calinan (Outbound)',
    route: lineString(CALINAN.OUTBOUND),
    color: '#A04002',
  },
  {
    name: 'Callawa (Inbound)',
    route: lineString(CALLAWA.INBOUND),
    color: '#873600',
  },
  {
    name: 'Callawa (Outbound)',
    route: lineString(CALLAWA.OUTBOUND),
    color: '#6C2E00',
  },
  {
    name: 'Catalunan Grande - Roxas (Inbound)',
    route: lineString(CATALUNAN_GRANDE.INBOUND),
    color: '#F1C40F',
  },
  {
    name: 'Catalunan Grande - Roxas (Outbound)',
    route: lineString(CATALUNAN_GRANDE.OUTBOUND),
    color: '#D4AC0D',
  },
  {
    name: 'Catitipan via Dacudao (Inbound)',
    route: lineString(CATITIPAN_DACUDAO.INBOUND),
    color: '#B7950B',
  },
  {
    name: 'Catitipan via Dacudao (Outbound)',
    route: lineString(CATITIPAN_DACUDAO.OUTBOUND),
    color: '#A04002',
  },
  {
    name: 'Catitipan via JP Laurel (Inbound)',
    route: lineString(CATITIPAN_JP_LAUREL.INBOUND),
    color: '#873600',
  },
  {
    name: 'Catitipan via JP Laurel (Outbound)',
    route: lineString(CATITIPAN_JP_LAUREL.OUTBOUND),
    color: '#6C2E00',
  },
  {
    name: 'Communal (Inbound)',
    route: lineString(COMMUNAL.INBOUND),
    color: '#F39C12',
  },
  {
    name: 'Communal (Outbound)',
    route: lineString(COMMUNAL.OUTBOUND),
    color: '#E67E22',
  },
  {
    name: 'Country Homes (Cabantian) (Inbound)',
    route: lineString(COUNTRY_HOMES.INBOUND),
    color: '#D68910',
  },
  {
    name: 'Country Homes (Cabantian) (Outbound)',
    route: lineString(COUNTRY_HOMES.OUTBOUND),
    color: '#B7950B',
  },
  {
    name: 'Deca Tacunan (Aircon) (Inbound)',
    route: lineString(DECA_TACUNAN_AIRCON.INBOUND),
    color: '#A04002',
  },
  {
    name: 'Deca Tacunan (Aircon) (Outbound)',
    route: lineString(DECA_TACUNAN_AIRCON.OUTBOUND),
    color: '#873600',
  },
  {
    name: 'Dona Pilar (Inbound)',
    route: lineString(DONA_PILAR.INBOUND),
    color: '#6C2E00',
  },
  {
    name: 'Dona Pilar (Outbound)',
    route: lineString(DONA_PILAR.OUTBOUND),
    color: '#512E5F',
  },
  {
    name: 'Ecoland - SM (Inbound)',
    route: lineString(ECOLAND_SM.INBOUND),
    color: '#27AE60',
  },
  {
    name: 'Ecoland - SM (Outbound)',
    route: lineString(ECOLAND_SM.OUTBOUND),
    color: '#229954',
  },
  {
    name: 'El Rio (Inbound)',
    route: lineString(EL_RIO.INBOUND),
    color: '#1E8449',
  },
  {
    name: 'El Rio (Outbound)',
    route: lineString(EL_RIO.OUTBOUND),
    color: '#186A3B',
  },
  {
    name: 'Emily Homes (Cabantian) (Inbound)',
    route: lineString(EMILY_HOMES_CABANTIAN.INBOUND),
    color: '#145A32',
  },
  {
    name: 'Emily Homes (Cabantian) (Outbound)',
    route: lineString(EMILY_HOMES_CABANTIAN.OUTBOUND),
    color: '#0E6655',
  },
  {
    name: 'Indangan (Inbound)',
    route: lineString(INDANGAN.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Indangan (Outbound)',
    route: lineString(INDANGAN.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Jade Valley - Bangkerohan (Inbound)',
    route: lineString(JADE_VALLEY_BANGKEROHAN.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Jade Valley - Bangkerohan (Outbound)',
    route: lineString(JADE_VALLEY_BANGKEROHAN.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Jade Valley - Buhangin (Inbound)',
    route: lineString(JADE_VALLEY_BUHANGIN.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Jade Valley - Buhangin (Outbound)',
    route: lineString(JADE_VALLEY_BUHANGIN.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Juliville (Inbound)',
    route: lineString(JULIVILLE.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Juliville (Outbound)',
    route: lineString(JULIVILLE.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Landmark 3 (Inbound)',
    route: lineString(LANDMARK_3.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Landmark 3 (Outbound)',
    route: lineString(LANDMARK_3.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Lasang via Buhangin (Inbound)',
    route: lineString(LASANG_BUHANGIN.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Lasang via Buhangin (Outbound)',
    route: lineString(LASANG_BUHANGIN.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Lasang via Sasa (Inbound)',
    route: lineString(LASANG_SASA.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Lasang via Sasa (Outbound)',
    route: lineString(LASANG_SASA.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Maa - Agdao (Inbound)',
    route: lineString(MAA_AGDAO.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Maa - Agdao (Outbound)',
    route: lineString(MAA_AGDAO.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Maa - Bangkerohan (Inbound)',
    route: lineString(MAA_BANGKEROHAN.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Maa - Bangkerohan (Outbound)',
    route: lineString(MAA_BANGKEROHAN.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Mahayag (Inbound)',
    route: lineString(MAHAYAG.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Mahayag (Outbound)',
    route: lineString(MAHAYAG.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Mandug (Inbound)',
    route: lineString(MANDUG.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Mandug (Outbound)',
    route: lineString(MANDUG.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Marahan - Roxas (Inbound)',
    route: lineString(MARAHAN.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Marahan - Roxas (Outbound)',
    route: lineString(MARAHAN.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Marilog - Roxas (Inbound)',
    route: lineString(MARILOG.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Marilog - Roxas (Outbound)',
    route: lineString(MARILOG.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Matina (Inbound)',
    route: lineString(MATINA.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Matina (Outbound)',
    route: lineString(MATINA.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Matina Aplaya (Inbound)',
    route: lineString(MATINA_APLAYA.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Matina Aplaya (Outbound)',
    route: lineString(MATINA_APLAYA.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Matina Crossing (Inbound)',
    route: lineString(MATINA_CROSSING.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Matina Crossing (Outbound)',
    route: lineString(MATINA_CROSSING.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Matina Pangi (Inbound)',
    route: lineString(MATINA_PANGI.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Matina Pangi (Outbound)',
    route: lineString(MATINA_PANGI.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Mintal - Roxas (Inbound)',
    route: lineString(MINTAL.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Mintal - Roxas (Outbound)',
    route: lineString(MINTAL.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Mulig (Toril) (Inbound)',
    route: lineString(MULIG_TORIL.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Mulig (Toril) (Outbound)',
    route: lineString(MULIG_TORIL.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Obrero (Inbound)',
    route: lineString(OBRERO.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Obrero (Outbound)',
    route: lineString(OBRERO.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Panabo - Davao City (Inbound)',
    route: lineString(PANABO.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Panabo - Davao City (Outbound)',
    route: lineString(PANABO.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Panabo City via Buhangin (Inbound)',
    route: lineString(PANABO_BUHANGIN.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Panabo City via Buhangin (Outbound)',
    route: lineString(PANABO_BUHANGIN.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Panacan via Cabaguio (Inbound)',
    route: lineString(PANACAN_CABAGUIO.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Panacan via Cabaguio (Outbound)',
    route: lineString(PANACAN_CABAGUIO.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Panacan via JP Laurel (Inbound)',
    route: lineString(PANACAN_JP_LAUREL.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Panacan via JP Laurel (Outbound)',
    route: lineString(PANACAN_JP_LAUREL.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Panacan - SM (Inbound)',
    route: lineString(PANACAN_SM.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Panacan - SM (Outbound)',
    route: lineString(PANACAN_SM.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Puan (Inbound)',
    route: lineString(PUAN.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Puan (Outbound)',
    route: lineString(PUAN.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Sasa via Cabaguio (Inbound)',
    route: lineString(SASA_CABAGUIO.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Sasa via Cabaguio (Outbound)',
    route: lineString(SASA_CABAGUIO.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Sasa via JP Laurel (Inbound)',
    route: lineString(SASA_JP_LAUREL.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Sasa via JP Laurel (Outbound)',
    route: lineString(SASA_JP_LAUREL.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Sasa via R. Castillo (Inbound)',
    route: lineString(SASA_R_CASTILLO.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Sasa via R. Castillo (Outbound)',
    route: lineString(SASA_R_CASTILLO.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Suraya Homes (Inbound)',
    route: lineString(SURAYA_HOMES.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Suraya Homes (Outbound)',
    route: lineString(SURAYA_HOMES.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Talomo - Roxas (Inbound)',
    route: lineString(TALOMO.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Talomo - Roxas (Outbound)',
    route: lineString(TALOMO.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Tibungco via Buhangin (Inbound)',
    route: lineString(TIBUNGCO_BUHANGIN.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Tibungco via Buhangin (Outbound)',
    route: lineString(TIBUNGCO_BUHANGIN.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Tibungco via Cabaguio (Inbound)',
    route: lineString(TIBUNGCO_CABAGUIO.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Tibungco via Cabaguio (Outbound)',
    route: lineString(TIBUNGCO_CABAGUIO.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Tibungco via R. Castillo (Inbound)',
    route: lineString(TIBUNGCO_R_CASTILLO.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Tibungco via R. Castillo (Outbound)',
    route: lineString(TIBUNGCO_R_CASTILLO.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Toril - Roxas (Inbound)',
    route: lineString(TORIL.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Toril - Roxas (Outbound)',
    route: lineString(TORIL.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Tugbok - Roxas (Inbound)',
    route: lineString(TUGBOK.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Tugbok - Roxas (Outbound)',
    route: lineString(TUGBOK.OUTBOUND),
    color: '#0A3D2C',
  },
  {
    name: 'Ulas - Magsaysay (Inbound)',
    route: lineString(ULAS.INBOUND),
    color: '#0B5345',
  },
  {
    name: 'Ulas - Magsaysay (Outbound)',
    route: lineString(ULAS.OUTBOUND),
    color: '#0A3D2C',
  },
];
