import { ACACIA_INBOUND, ACACIA_OUTBOUND } from "./route-coordinates/acacia";
import {
  BUHANGIN_VIA_DACUDAO_INBOUND,
  BUHANGIN_VIA_DACUDAO_OUTBOUND,
} from "./route-coordinates/buhangin-dacudao";
import {
  BUHANGIN_VIA_JP_LAUREL_INBOUND,
  BUHANGIN_VIA_JP_LAUREL_OUTBOUND,
} from "./route-coordinates/buhangin-jp-laurel";
import {
  INDANGAN_INBOUND,
  INDANGAN_OUTBOUND,
} from "./route-coordinates/indangan";

export const ACACIA = {
  INBOUND: ACACIA_INBOUND,
  OUTBOUND: ACACIA_OUTBOUND,
};

export const BUHANGIN_VIA_JP_LAUREL = {
  INBOUND: BUHANGIN_VIA_JP_LAUREL_INBOUND,
  OUTBOUND: BUHANGIN_VIA_JP_LAUREL_OUTBOUND,
};

export const BUHANGIN_VIA_DACUDAO = {
  INBOUND: BUHANGIN_VIA_DACUDAO_INBOUND,
  OUTBOUND: BUHANGIN_VIA_DACUDAO_OUTBOUND,
};

export const INDANGAN = {
  INBOUND: INDANGAN_INBOUND,
  OUTBOUND: INDANGAN_OUTBOUND,
};
